# 動作確認用
name: daily-notifier


on:
  workflow_dispatch:

  # schedule:
  #   - cron: '0,30 * * * *'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: daily-notifier mail send
        env:
          MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
        run: python main.py